/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 34
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_separator = 1,
  sym_comment = 2,
  aux_sym_newline_token1 = 3,
  sym_status_code = 4,
  aux_sym_reason_phrase_token1 = 5,
  sym_method = 6,
  sym_url = 7,
  sym_http_version = 8,
  anon_sym_COLON = 9,
  sym_header_name = 10,
  sym_body = 11,
  sym_document = 12,
  sym_newline = 13,
  sym_response = 14,
  sym_response_status_line = 15,
  sym_reason_phrase = 16,
  sym_request = 17,
  sym_request_line = 18,
  sym_header = 19,
  sym_header_value = 20,
  aux_sym_document_repeat1 = 21,
  aux_sym_response_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_separator] = "separator",
  [sym_comment] = "comment",
  [aux_sym_newline_token1] = "newline_token1",
  [sym_status_code] = "status_code",
  [aux_sym_reason_phrase_token1] = "reason_phrase_token1",
  [sym_method] = "method",
  [sym_url] = "url",
  [sym_http_version] = "http_version",
  [anon_sym_COLON] = ":",
  [sym_header_name] = "header_name",
  [sym_body] = "body",
  [sym_document] = "document",
  [sym_newline] = "newline",
  [sym_response] = "response",
  [sym_response_status_line] = "response_status_line",
  [sym_reason_phrase] = "reason_phrase",
  [sym_request] = "request",
  [sym_request_line] = "request_line",
  [sym_header] = "header",
  [sym_header_value] = "header_value",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_response_repeat1] = "response_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_separator] = sym_separator,
  [sym_comment] = sym_comment,
  [aux_sym_newline_token1] = aux_sym_newline_token1,
  [sym_status_code] = sym_status_code,
  [aux_sym_reason_phrase_token1] = aux_sym_reason_phrase_token1,
  [sym_method] = sym_method,
  [sym_url] = sym_url,
  [sym_http_version] = sym_http_version,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_header_name] = sym_header_name,
  [sym_body] = sym_body,
  [sym_document] = sym_document,
  [sym_newline] = sym_newline,
  [sym_response] = sym_response,
  [sym_response_status_line] = sym_response_status_line,
  [sym_reason_phrase] = sym_reason_phrase,
  [sym_request] = sym_request,
  [sym_request_line] = sym_request_line,
  [sym_header] = sym_header,
  [sym_header_value] = sym_header_value,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_response_repeat1] = aux_sym_response_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_newline_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_status_code] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_reason_phrase_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_url] = {
    .visible = true,
    .named = true,
  },
  [sym_http_version] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_header_name] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_response] = {
    .visible = true,
    .named = true,
  },
  [sym_response_status_line] = {
    .visible = true,
    .named = true,
  },
  [sym_reason_phrase] = {
    .visible = true,
    .named = true,
  },
  [sym_request] = {
    .visible = true,
    .named = true,
  },
  [sym_request_line] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_header_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_response_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 5,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 10,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 20,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 29,
  [33] = 24,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        '\n', 49,
        '\r', 1,
        '#', 46,
        ':', 59,
        'C', 79,
        'D', 67,
        'G', 68,
        'H', 69,
        'O', 82,
        'P', 62,
        'T', 83,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '5')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(49);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(48);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(48);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 4:
      if (lookahead == 'A') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 'A') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == 'A') ADVANCE(32);
      if (lookahead == 'O') ADVANCE(28);
      if (lookahead == 'U') ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == 'C') ADVANCE(30);
      END_STATE();
    case 8:
      if (lookahead == 'C') ADVANCE(17);
      END_STATE();
    case 9:
      if (lookahead == 'C') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'D') ADVANCE(53);
      END_STATE();
    case 11:
      if (lookahead == 'E') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == 'E') ADVANCE(30);
      END_STATE();
    case 13:
      if (lookahead == 'E') ADVANCE(4);
      if (lookahead == 'T') ADVANCE(33);
      END_STATE();
    case 14:
      if (lookahead == 'E') ADVANCE(53);
      END_STATE();
    case 15:
      if (lookahead == 'E') ADVANCE(7);
      END_STATE();
    case 16:
      if (lookahead == 'E') ADVANCE(34);
      END_STATE();
    case 17:
      if (lookahead == 'H') ADVANCE(53);
      END_STATE();
    case 18:
      if (lookahead == 'I') ADVANCE(24);
      END_STATE();
    case 19:
      if (lookahead == 'L') ADVANCE(16);
      END_STATE();
    case 20:
      if (lookahead == 'N') ADVANCE(22);
      END_STATE();
    case 21:
      if (lookahead == 'N') ADVANCE(29);
      END_STATE();
    case 22:
      if (lookahead == 'N') ADVANCE(15);
      END_STATE();
    case 23:
      if (lookahead == 'O') ADVANCE(20);
      END_STATE();
    case 24:
      if (lookahead == 'O') ADVANCE(21);
      END_STATE();
    case 25:
      if (lookahead == 'P') ADVANCE(56);
      END_STATE();
    case 26:
      if (lookahead == 'P') ADVANCE(31);
      END_STATE();
    case 27:
      if (lookahead == 'R') ADVANCE(5);
      END_STATE();
    case 28:
      if (lookahead == 'S') ADVANCE(30);
      END_STATE();
    case 29:
      if (lookahead == 'S') ADVANCE(53);
      END_STATE();
    case 30:
      if (lookahead == 'T') ADVANCE(53);
      END_STATE();
    case 31:
      if (lookahead == 'T') ADVANCE(18);
      END_STATE();
    case 32:
      if (lookahead == 'T') ADVANCE(8);
      END_STATE();
    case 33:
      if (lookahead == 'T') ADVANCE(25);
      END_STATE();
    case 34:
      if (lookahead == 'T') ADVANCE(14);
      END_STATE();
    case 35:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(35);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(55);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 38:
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 39:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        '\n', 48,
        '\r', 2,
        '#', 46,
        'C', 79,
        'D', 67,
        'G', 68,
        'H', 69,
        'O', 82,
        'P', 62,
        'T', 83,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 40:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        '\n', 48,
        '\r', 2,
        '#', 46,
        'C', 23,
        'D', 11,
        'G', 12,
        'H', 13,
        'O', 26,
        'P', 6,
        'T', 27,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_separator);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_separator);
      if (lookahead == '\n') ADVANCE(42);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '#') ADVANCE(43);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '#') ADVANCE(45);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_newline_token1);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_newline_token1);
      if (lookahead != 0) ADVANCE(92);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_status_code);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_reason_phrase_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_reason_phrase_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_method);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_method);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_url);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_http_version);
      if (lookahead == '/') ADVANCE(38);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_http_version);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_http_version);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'A') ADVANCE(66);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'A') ADVANCE(65);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'A') ADVANCE(88);
      if (lookahead == 'O') ADVANCE(84);
      if (lookahead == 'U') ADVANCE(86);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'C') ADVANCE(86);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'C') ADVANCE(73);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'C') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'D') ADVANCE(54);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'E') ADVANCE(75);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'E') ADVANCE(86);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'E') ADVANCE(60);
      if (lookahead == 'T') ADVANCE(89);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'E') ADVANCE(54);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'E') ADVANCE(63);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'E') ADVANCE(90);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'H') ADVANCE(54);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'I') ADVANCE(80);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'L') ADVANCE(72);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'N') ADVANCE(78);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'N') ADVANCE(85);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'N') ADVANCE(71);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'O') ADVANCE(76);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'O') ADVANCE(77);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'P') ADVANCE(57);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'P') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'R') ADVANCE(61);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'S') ADVANCE(86);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'S') ADVANCE(54);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'T') ADVANCE(54);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'T') ADVANCE(74);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'T') ADVANCE(64);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'T') ADVANCE(81);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == 'T') ADVANCE(70);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_body);
      if (lookahead != 0) ADVANCE(92);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 40},
  [2] = {.lex_state = 40},
  [3] = {.lex_state = 40},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 39},
  [8] = {.lex_state = 39},
  [9] = {.lex_state = 39},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 39},
  [14] = {.lex_state = 39},
  [15] = {.lex_state = 39},
  [16] = {.lex_state = 40},
  [17] = {.lex_state = 40},
  [18] = {.lex_state = 40},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 40},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 35},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 40},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 40},
  [28] = {.lex_state = 40},
  [29] = {.lex_state = 40},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 40},
  [32] = {.lex_state = 40},
  [33] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_separator] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [aux_sym_newline_token1] = ACTIONS(1),
    [sym_status_code] = ACTIONS(1),
    [sym_method] = ACTIONS(1),
    [sym_http_version] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_header_name] = ACTIONS(1),
    [sym_body] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(26),
    [sym_newline] = STATE(2),
    [sym_response] = STATE(2),
    [sym_response_status_line] = STATE(4),
    [sym_request] = STATE(2),
    [sym_request_line] = STATE(7),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_separator] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [aux_sym_newline_token1] = ACTIONS(9),
    [sym_method] = ACTIONS(11),
    [sym_http_version] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym_newline] = STATE(3),
    [sym_response] = STATE(3),
    [sym_response_status_line] = STATE(4),
    [sym_request] = STATE(3),
    [sym_request_line] = STATE(7),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_separator] = ACTIONS(17),
    [sym_comment] = ACTIONS(19),
    [aux_sym_newline_token1] = ACTIONS(9),
    [sym_method] = ACTIONS(11),
    [sym_http_version] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym_newline] = STATE(3),
    [sym_response] = STATE(3),
    [sym_response_status_line] = STATE(4),
    [sym_request] = STATE(3),
    [sym_request_line] = STATE(7),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_separator] = ACTIONS(23),
    [sym_comment] = ACTIONS(26),
    [aux_sym_newline_token1] = ACTIONS(29),
    [sym_method] = ACTIONS(32),
    [sym_http_version] = ACTIONS(35),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(42), 1,
      sym_header_name,
    ACTIONS(44), 1,
      sym_body,
    ACTIONS(38), 2,
      ts_builtin_sym_end,
      sym_separator,
    STATE(6), 2,
      sym_header,
      aux_sym_response_repeat1,
    ACTIONS(40), 4,
      sym_comment,
      aux_sym_newline_token1,
      sym_method,
      sym_http_version,
  [21] = 4,
    ACTIONS(50), 1,
      sym_header_name,
    ACTIONS(46), 2,
      ts_builtin_sym_end,
      sym_separator,
    STATE(5), 2,
      sym_header,
      aux_sym_response_repeat1,
    ACTIONS(48), 5,
      sym_comment,
      aux_sym_newline_token1,
      sym_method,
      sym_http_version,
      sym_body,
  [40] = 5,
    ACTIONS(42), 1,
      sym_header_name,
    ACTIONS(57), 1,
      sym_body,
    ACTIONS(53), 2,
      ts_builtin_sym_end,
      sym_separator,
    STATE(5), 2,
      sym_header,
      aux_sym_response_repeat1,
    ACTIONS(55), 4,
      sym_comment,
      aux_sym_newline_token1,
      sym_method,
      sym_http_version,
  [61] = 4,
    ACTIONS(63), 1,
      sym_header_name,
    STATE(8), 2,
      sym_header,
      aux_sym_response_repeat1,
    ACTIONS(59), 3,
      ts_builtin_sym_end,
      sym_separator,
      aux_sym_newline_token1,
    ACTIONS(61), 3,
      sym_comment,
      sym_method,
      sym_http_version,
  [79] = 4,
    ACTIONS(63), 1,
      sym_header_name,
    STATE(9), 2,
      sym_header,
      aux_sym_response_repeat1,
    ACTIONS(65), 3,
      ts_builtin_sym_end,
      sym_separator,
      aux_sym_newline_token1,
    ACTIONS(67), 3,
      sym_comment,
      sym_method,
      sym_http_version,
  [97] = 4,
    ACTIONS(69), 1,
      sym_header_name,
    STATE(9), 2,
      sym_header,
      aux_sym_response_repeat1,
    ACTIONS(46), 3,
      ts_builtin_sym_end,
      sym_separator,
      aux_sym_newline_token1,
    ACTIONS(48), 3,
      sym_comment,
      sym_method,
      sym_http_version,
  [115] = 2,
    ACTIONS(72), 2,
      ts_builtin_sym_end,
      sym_separator,
    ACTIONS(74), 6,
      sym_comment,
      aux_sym_newline_token1,
      sym_method,
      sym_http_version,
      sym_header_name,
      sym_body,
  [128] = 2,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      sym_separator,
    ACTIONS(78), 6,
      sym_comment,
      aux_sym_newline_token1,
      sym_method,
      sym_http_version,
      sym_header_name,
      sym_body,
  [141] = 2,
    ACTIONS(80), 2,
      ts_builtin_sym_end,
      sym_separator,
    ACTIONS(82), 6,
      sym_comment,
      aux_sym_newline_token1,
      sym_method,
      sym_http_version,
      sym_header_name,
      sym_body,
  [154] = 2,
    ACTIONS(84), 3,
      ts_builtin_sym_end,
      sym_separator,
      aux_sym_newline_token1,
    ACTIONS(86), 4,
      sym_comment,
      sym_method,
      sym_http_version,
      sym_header_name,
  [166] = 2,
    ACTIONS(72), 3,
      ts_builtin_sym_end,
      sym_separator,
      aux_sym_newline_token1,
    ACTIONS(74), 4,
      sym_comment,
      sym_method,
      sym_http_version,
      sym_header_name,
  [178] = 2,
    ACTIONS(88), 3,
      ts_builtin_sym_end,
      sym_separator,
      aux_sym_newline_token1,
    ACTIONS(90), 4,
      sym_comment,
      sym_method,
      sym_http_version,
      sym_header_name,
  [190] = 2,
    ACTIONS(94), 1,
      sym_comment,
    ACTIONS(92), 5,
      ts_builtin_sym_end,
      sym_separator,
      aux_sym_newline_token1,
      sym_method,
      sym_http_version,
  [201] = 2,
    ACTIONS(55), 1,
      sym_comment,
    ACTIONS(53), 5,
      ts_builtin_sym_end,
      sym_separator,
      aux_sym_newline_token1,
      sym_method,
      sym_http_version,
  [212] = 2,
    ACTIONS(98), 1,
      sym_comment,
    ACTIONS(96), 5,
      ts_builtin_sym_end,
      sym_separator,
      aux_sym_newline_token1,
      sym_method,
      sym_http_version,
  [223] = 3,
    ACTIONS(100), 1,
      aux_sym_newline_token1,
    ACTIONS(102), 1,
      aux_sym_reason_phrase_token1,
    STATE(28), 1,
      sym_reason_phrase,
  [233] = 2,
    ACTIONS(104), 1,
      aux_sym_reason_phrase_token1,
    STATE(29), 1,
      sym_header_value,
  [240] = 2,
    ACTIONS(106), 1,
      aux_sym_newline_token1,
    ACTIONS(108), 1,
      sym_http_version,
  [247] = 2,
    ACTIONS(104), 1,
      aux_sym_reason_phrase_token1,
    STATE(32), 1,
      sym_header_value,
  [254] = 1,
    ACTIONS(110), 1,
      sym_url,
  [258] = 1,
    ACTIONS(112), 1,
      anon_sym_COLON,
  [262] = 1,
    ACTIONS(114), 1,
      aux_sym_newline_token1,
  [266] = 1,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
  [270] = 1,
    ACTIONS(118), 1,
      aux_sym_newline_token1,
  [274] = 1,
    ACTIONS(120), 1,
      aux_sym_newline_token1,
  [278] = 1,
    ACTIONS(122), 1,
      aux_sym_newline_token1,
  [282] = 1,
    ACTIONS(124), 1,
      sym_status_code,
  [286] = 1,
    ACTIONS(126), 1,
      aux_sym_newline_token1,
  [290] = 1,
    ACTIONS(128), 1,
      aux_sym_newline_token1,
  [294] = 1,
    ACTIONS(130), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 21,
  [SMALL_STATE(6)] = 40,
  [SMALL_STATE(7)] = 61,
  [SMALL_STATE(8)] = 79,
  [SMALL_STATE(9)] = 97,
  [SMALL_STATE(10)] = 115,
  [SMALL_STATE(11)] = 128,
  [SMALL_STATE(12)] = 141,
  [SMALL_STATE(13)] = 154,
  [SMALL_STATE(14)] = 166,
  [SMALL_STATE(15)] = 178,
  [SMALL_STATE(16)] = 190,
  [SMALL_STATE(17)] = 201,
  [SMALL_STATE(18)] = 212,
  [SMALL_STATE(19)] = 223,
  [SMALL_STATE(20)] = 233,
  [SMALL_STATE(21)] = 240,
  [SMALL_STATE(22)] = 247,
  [SMALL_STATE(23)] = 254,
  [SMALL_STATE(24)] = 258,
  [SMALL_STATE(25)] = 262,
  [SMALL_STATE(26)] = 266,
  [SMALL_STATE(27)] = 270,
  [SMALL_STATE(28)] = 274,
  [SMALL_STATE(29)] = 278,
  [SMALL_STATE(30)] = 282,
  [SMALL_STATE(31)] = 286,
  [SMALL_STATE(32)] = 290,
  [SMALL_STATE(33)] = 294,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_response, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_response, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_response_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_response_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_response_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_response, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_response, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request, 2, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_response_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 4, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 4, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_response_status_line, 3, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_response_status_line, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_response_status_line, 4, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_response_status_line, 4, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_line, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request_line, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_line, 4, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request_line, 4, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_newline, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_newline, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_response, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_response, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [116] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reason_phrase, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_value, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_http(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
